#!/bin/bash
# script to test different configure options

python3 liverlevelset-exact.py --builddb --dbfile=trainingdata_one.csv
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-actualkappa/alpha0beta0gamma1 --gamma --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-actualkappa/alpha0beta1gamma1 --beta --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-actualkappa/alpha0beta1gamma1 --beta --gamma --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-actualkappa/alpha1beta0gamma0 --alpha --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-actualkappa/alpha1beta1gamma0 --alpha --beta  --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-actualkappa/alpha1beta0gamma1 --alpha --gamma --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-actualkappa/alpha1beta1gamma1 --alpha --beta --gamma --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-actualkappa/alpha0beta0gamma1 --gamma --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-actualkappa/alpha0beta1gamma1 --beta --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-actualkappa/alpha0beta1gamma1 --beta --gamma --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-actualkappa/alpha1beta0gamma0 --alpha --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-actualkappa/alpha1beta1gamma0 --alpha --beta  --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir==modelout/lsn-exact/comparison/learnededge-actualkappa/alpha1beta0gamma1 --alpha --gamma --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-actualkappa/alpha1beta1gamma1 --alpha --beta --gamma --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-learnedkappa/alpha0beta0gamma1 --gamma --learned_kappakernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-learnedkappa/alpha0beta1gamma1 --beta --learned_kappakernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-learnedkappa/alpha0beta1gamma1 --beta --gamma --learned_kappakernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-learnedkappa/alpha1beta0gamma0 --alpha --learned_kappakernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-learnedkappa/alpha1beta1gamma0 --alpha --beta  --learned_kappakernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-learnedkappa/alpha1beta0gamma1 --alpha --gamma --learned_kappakernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/actualedge-learnedkappa/alpha1beta1gamma1 --alpha --beta --gamma --learned_kappakernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-learnedkappa/alpha0beta0gamma1 --gamma --learned_kappakernel --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-learnedkappa/alpha0beta1gamma1 --beta --learned_kappakernel --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-learnedkappa/alpha0beta1gamma1 --beta --gamma --learned_kappakernel --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-learnedkappa/alpha1beta0gamma0 --alpha --learned_kappakernel --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-learnedkappa/alpha1beta1gamma0 --alpha --beta  --learned_kappakernel --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-learnedkappa/alpha1beta0gamma1 --alpha --gamma --learned_kappakernel --learned_edgekernel --circlerad=30
python3 liverlevelset-exact.py --dbfile=trainingdata_one.csv --numepochs=20 --nt=80 --trainingbatch=1 --circleinit --kfolds=5 --idfold=1 --outdir=modelout/lsn-exact/comparison/learnededge-learnedkappa/alpha1beta1gamma1 --alpha --beta --gamma --learned_kappakernel --learned_edgekernel --circlerad=30
